<a href="https://colab.research.google.com/github/chaimahmida/matrix_git/blob/main/First_git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Matrix
---



In [ ]:

import numpy as np
from scipy import stats as st
matrix=np.array([[1, 2, 3], [4, 2, 6], [7, 8, 9]])
print("voila ma matrice :",matrix)


voila ma matrice : [[1 2 3]
 [4 2 6]
 [7 8 9]]


In [ ]:



mean_value=np.mean(matrix)
print("la moyenne de la matrice est :",mean_value)


median_value=np.median(matrix)
print("la mediane de la matrice est :",median_value)



la moyenne de la matrice est : 4.666666666666667
la mediane de la matrice est : 4.0


In [ ]:
mode_value=st.mode(matrix,axis=None, keepdims=False)
print("le mode de la matrice est :",mode_value)

le mode de la matrice est : ModeResult(mode=2, count=2)


In [ ]:
lista=np.array([-2.5, 99 ,0,10.5,2024])
lista

array([  -2.5,   99. ,    0. ,   10.5, 2024. ])

In [ ]:
print("max=",max(lista) ,"min=",min(lista))

max= 2024 min= -2.5


In [ ]:
sum(lista)

2131.0

In [ ]:
print("le premier élement est :",lista[0])

le premier élement est : -2.5


In [ ]:
A=np.sort(lista)
A

array([  -2.5,    0. ,   10.5,   99. , 2024. ])

In [ ]:
l=lista.sort()
print(l)

None


In [1]:
!git init


hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [2]:
!git add /content/drive/MyDrive/checkpoint.ipynb #ipynb jupyter file (extension)

In [3]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   drive/MyDrive/checkpoint.ipynb

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    drive/MyDrive/checkpoint.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	"drive/MyDrive/Carte e\314\201lectronique /"
	drive/MyDrive/First_Colab_File.ipynb
	drive/MyDrive/Projet tp3_G4.gdoc
	drive/MyDrive/Untitled0.ipynb
	drive/MyDrive/Vlsi/
	drive/MyDrive/olfa amal PFE ing.pptx
	drive/MyDrive/presentation gomycode/
	sample_data/



In [4]:
!git commit -m "initial commit at 8pm 24 october "

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@e8177a33b464.(none)')


In [10]:
!git config --global user.email "chaima.hmida1995@gmail.com"
!git config --global user.name "chaimahmida"

In [11]:
!git commit -m " seconde commit"

[master (root-commit) aa65526]  seconde commit
 1 file changed, 1 insertion(+)
 create mode 100644 drive/MyDrive/checkpoint.ipynb


In [13]:
import numpy
numpy.__version__

'1.26.4'

In [14]:
!git commit -m "initial commit after numpy"

On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    drive/MyDrive/checkpoint.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	"drive/MyDrive/Carte e\314\201lectronique /"
	drive/MyDrive/First_Colab_File.ipynb
	drive/MyDrive/Projet tp3_G4.gdoc
	drive/MyDrive/Untitled0.ipynb
	drive/MyDrive/Vlsi/
	drive/MyDrive/olfa amal PFE ing.pptx
	drive/MyDrive/presentation gomycode/
	sample_data/

no changes added to commit (use "git add" and/or "git commit -a")
